### ISSUE TITLE
 error: (-215:Assertion failed) !ssize.empty() in function 'resize'

### ISSUE THREAD

**Issue by zouxiaodong** [Kedreamix/PaddleAvatar#1]
2023-06-22 08:39:51.174 Uncaught app exception
Traceback (most recent call last):
  File "/data/conda/avatar/lib/python3.8/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "/data/conda/avatar/PaddleAvatar/avatar.streamlit.py", line 169, in <module>
    fom(face.name,'zimeng.mp4')
  File "/data/conda/avatar/PaddleAvatar/avatar.streamlit.py", line 125, in fom
    fom_predictor.run(input_face, driving_video)
  File "/data/conda/avatar/lib/python3.8/site-packages/ppgan/apps/first_order_predictor.py", line 190, in run
    face_image = cv2.resize(face_image, (self.image_size, self.image_size)) / 255.0
cv2.error: OpenCV(4.7.0) /io/opencv/modules/imgproc/src/resize.cpp:4062: error: (-215:Assertion failed) !ssize.empty() in function 'resize'

**Comment by Kedreamix** [comment]
这个应该是opencv的般般问题，可以按照4.5.*的般般尝试一下
