### ISSUE TITLE
Got a problem, "The registered buffer should be a Paddle.Tensor, but received Variable. ", how to fix it

### ISSUE THREAD

**Issue by zsmszsms** [Kedreamix/PaddleAvatar#5]
[12/18 16:15:09] ppgan INFO: Found /home/wmao/.cache/ppgan/vox-cpk.pdparams
2023-12-18 16:15:09.347 Uncaught app exception
Traceback (most recent call last):
  File "/home/wmao/.local/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
  File "/data/PaddleAvatar/avatar.streamlit.py", line 169, in <module>
    fom(face.name,'zimeng.mp4')
  File "/data/PaddleAvatar/avatar.streamlit.py", line 119, in fom
    fom_predictor = FirstOrderPredictor(filename = output,
  File "/home/wmao/.local/lib/python3.9/site-packages/ppgan/apps/first_order_predictor.py", line 114, in __init__
    self.generator, self.kp_detector = self.load_checkpoints(
  File "/home/wmao/.local/lib/python3.9/site-packages/ppgan/apps/first_order_predictor.py", line 225, in load_checkpoints
    generator = OcclusionAwareGenerator(
  File "/home/wmao/.local/lib/python3.9/site-packages/ppgan/models/generators/occlusion_aware.py", line 35, in __init__
    self.dense_motion_network = DenseMotionNetwork(
  File "/home/wmao/.local/lib/python3.9/site-packages/ppgan/modules/dense_motion.py", line 93, in __init__
    self.down = AntiAliasInterpolation2d(num_channels,
  File "/home/wmao/.local/lib/python3.9/site-packages/ppgan/modules/first_order.py", line 457, in __init__
    self.register_buffer('weight', kernel)
  File "/home/wmao/.local/lib/python3.9/site-packages/paddle/nn/layer/layers.py", line 1075, in register_buffer
    raise TypeError(
TypeError: The registered buffer should be a Paddle.Tensor, but received Variable.

**Comment by Qi-Y** [comment]
The same problem !

**Comment by Kedreamix** [comment]
Could you please share your development environments?

**Comment by Kedreamix** [comment]
you can try my new project: https://github.com/Kedreamix/Linly-Talker
